### ISSUE TITLE
Not an issue, rather question for help... (using own crafted JSON to publish)

### ISSUE THREAD

**Issue by icepaule** [vxunderground/ThreatIntelligenceDiscordBot#12]
Hello VX,

in the need to use your great bot at my own discord, I was wondering if I could publish my own created json to the bot as well.

But something like the below does not work and I'm not in python at all. :-/
Could you give me a hand in how to publish my own created json, please?

Thx so much
Marcus

_source_details = {
    "My Feed": {
        "source": "file:///opt/ThreatIntelligenceDiscordBot/OSINT.json",
        "hook": my_news,
        "type": FeedTypes.JSON,
    },
}_

ERROR:
requests.exceptions.InvalidSchema: No connection adapters were found for 'file:///opt/ThreatIntelligenceDiscordBot/OSINT.json'

**Comment by vxunderground** [comment]
It is designed to come from an RSS feed.
