### ISSUE TITLE
support for configuration file

### ISSUE THREAD

**Issue by Mycah** [vxunderground/ThreatIntelligenceDiscordBot#14]
I would like to see support for a configuration file with my discord links so I don't have to modify the source.

Thanks!

**Comment by vxunderground** [comment]
+

**Comment by bertmad3400** [comment]
I'm looking into implementing this, shouldn't be too difficult

**Comment by bertmad3400** [comment]
This is to be resolved by #15, once it gets merged.

**Comment by Mycah** [comment]
Wonderful, thank you!

**Comment by bertmad3400** [comment]
#15 didn't end up merged to upstream, but have rebased upon the latest updates and added some new features in #17
