### ISSUE TITLE
requirements.txt please?

### ISSUE THREAD

**Issue by Mycah** [vxunderground/ThreatIntelligenceDiscordBot#2]
I'd love a requirements.txt to install required libs and versions.  I just did an update to ubuntu 22.04 and now i see this after a pip install discord:

```
$ ./DiscordIntelBot.py
Traceback (most recent call last):
  File "/home/xxxx/ThreatIntelligenceDiscordBot/Source/./DiscordIntelBot.py", line 7, in <module>
    from discord import Webhook, RequestsWebhookAdapter
ImportError: cannot import name 'RequestsWebhookAdapter' from 'discord' (/usr/local/lib/python3.10/dist-packages/discord/__init__.py)

```

I imagine its due to a mismatched version?  pip install discord installed `discord.py-2.0.0`

**Comment by vxunderground** [comment]
Someone resolved the issue via

python3 -m pip install --force-reinstall "discord.py<=1.0.0"

&& Yes, agreed, a requirements.txt should be added.

**Comment by Mycah** [comment]
`pip install -Iv discord.py==1.7.3` ended up working for me.
