### ISSUE TITLE
Regarding OSINTer...

### ISSUE THREAD

**Issue by bertmad3400** [vxunderground/ThreatIntelligenceDiscordBot#6]
*I don't know if this is the right place to write this, but as I wasn't able to get in contact with smelly__vx through other means, I thought that this might not be too bad of a place. @vxunderground, if you have seen my original message and is tired of me spamming this everywhere, please let me know, and I will promptly stop. With that out the way, let's get on with it.*

#### Hi There!

I'm writing this, in the hopes that some of you might find it interesting in relation to this Discord Bot. To cut to the chase, I have for the last year or so, I have been working with two specalists within the CTI field, who (at the time) was working at the swedish cybersecurity firm Combitech on a project called OSINTer. The purpose of OSINTer was to unify all, or most of the relevant news sources regarding cybersecurity and related fields in one place, and in one generic and streamlined package, which would greatly reduce the amount of work needed to collect valuable intel for CTI and related fields. This started as nothing more than a simple python script, designed to just collect information from a few sources, but has since grown into a rather sophisticated news aggregator, with the ability to collect, handle and organize substantial amounts of data and touching nearly every part of the stack, from the very backend using Ansible, Elasticsearch and Python/FastAPI to the very frontend using Svelte.

Now the reason I'm writing here is due to the rather substantial - and probably obvious - similarities between OSINTer and this this Discord Bot. While they do utilize rather different approaches for collecting information (with OSINTer using an assortment of scraping techniques in combination with browser emulation and JS injection) and rather different approach to present this data to the user (with OSINTer using a graphical client-side rendered webpage along with a series of REST api's), the overall goal is much the same ([I even at one point developed a discord bot for OSINTer,](https://gitlab.com/osinter/discord-bot), though that is no longer maintained), and I therefore thought that there might grounds for some collaboration between the two projects. The current version of OSINTer is - due to some legal issues - unfortunately not open-source, but it's still source-available, has a long history of being open-source and I have a strong personal ambition of one day getting to the point where I can again classify OSINTer as open-source and as such, it hope the current missing license won't be to much of a problem.

Hope some of you found this interresting. If you did, an up-to-date demo of the project can be found at [dev.osinter.dk/](https://dev.osinter.dk/) (or [osinter.dk](https://osinter.dk) should the former be down) and the source code at https://gitlab.com/osinter/

**Comment by vxunderground** [comment]
Please contact smelly via any method listed below. Thanks.

Telegram: https://t.me/smellyvx
Discord: smelly__vx#0001
